job_str: |-
  units metal
  boundary p p p
  atom_style atomic

  read_data $DATA$

  pair_style eam/fs
  pair_coeff * * $FILE$ $ELEM$

  neighbor 2.0 bin
  neigh_modify delay 10 check yes


  dump 1 all xyz 2000 $NAME$.xyz
  dump_modify 1 element $ELEM$
  dump_modify 1 sort id

  dump 2 all custom 2000 $NAME$_wbox.dump id type x y z
  dump_modify 2 element $ELEM$

  thermo 10
  thermo_style custom pe temp

  min_style cg 
  minimize 1e-25 1e-25 5000 10000

  timestep 0.001
  velocity all set 0.0 0.0 0.0

  fix 1 all nve
  run 20000
  unfix 1

  fix 2 all nvt temp 300.0 300.0 0.1
  fix 3 all recenter INIT INIT INIT units box

  run 200000