job_str: |-
  units metal
  boundary p p p
  atom_style atomic

  read_data $DATA$

  pair_style meam
  pair_coeff * * $FILE1$ $FF_ELEM$ $FILE2$ $ELEM$

  neighbor 2.0 bin
  neigh_modify delay 10 check yes

  group niti type 1 2
  group cr type 3

  dump 1 all xyz 10000 $NAME$.xyz
  dump_modify 1 element $ELEM$

  dump 2 all xyz 5000000 $NAME$_frames.xyz
  dump_modify 2 element $ELEM$

  thermo 10
  timestep 0.001

  fix 1 all box/relax aniso 0.0 vmax 0.001
  min_style cg 
  minimize 1e-25 1e-25 5000 10000
  unfix 1
  fix 1 all nve
  run 500000
  unfix 1

  fix push niti smd cvel 4.336e-7 1e-9 couple cr -1.0 0.0 0.0 15.0

  thermo_style custom step pe temp f_push[6] f_push[7]
  fix eq all nve
  run 750000000

  write_restart $NAME$.restart