job_str: |-
  units metal
  boundary p p p
  atom_style atomic

  read_data $DATA$

  pair_style meam
  pair_coeff * * $FILE1$ $FF_ELEM$ $FILE2$ $FF_ELEM$

  neighbor 2.0 bin

  group ni type 1

  dump 1 all xyz 2000 $NAME$.xyz
  dump_modify 1 element $FF_ELEM$
  dump_modify 1 sort id

  dump 2 all custom 2000 $NAME$_wbox.dump id type x y z
  dump_modify 2 element $FF_ELEM$

  thermo 10
  thermo_style custom pe temp

  timestep 0.001

  min_style quickmin 
  minimize 1e-25 1e-25 5000 10000

  neigh_modify delay 10 check yes
  
  velocity all set 0.0 0.0 0.0

  fix 1 all nve
  run 20000
  unfix 1

  thermo_style custom step pe temp

  fix 2 all nvt temp 300.0 300.0 0.1
  compute 1 all stress/atom NULL pair
  fix 3 all recenter INIT INIT INIT units box

  dump 3 all custom 2000 $NAME$_stress.dump id type x y z c_1[*]
  dump_modify 3 element $FF_ELEM$
  dump_modify 3 sort id

  run 200000