job_str: |-
  units metal
  boundary p p p
  atom_style atomic

  read_data $DATA$

  pair_style meam
  pair_coeff * * $FILE1$ Ni Ti Cr $FILE2$ Ni Ti Cr

  neighbor 2.0 bin
  neigh_modify delay 10 check yes

  group niti type 1 2
  group cr type 3

  dump 1 all xyz 10000 $NAME$.xyz
  dump_modify 1 element Ni Ti Cr

  dump 2 all xyz 5000000 $NAME$_frames.xyz
  dump_modify 2 element Ni Ti Cr

  fix push niti smd cvel 4.336e-9 1e-9 couple cr -1.0 0.0 0.0 15.0
  # 4.336 - 0.004336

  thermo 50
  thermo_style custom etotal pe temp f_push[6] f_push[7]

  timestep 0.0001

  fix eq all nvt temp 300.0 300.0 0.1
  # run 1000000000
  run 750000000

  write_restart $NAME$.restart
  # unfix eq