job_name: interface_rel_metal
sim: md
elems: Ni Ti Cr
xyz: interface.xyz
system_bounds: [[-31.4273, -8.51501, -6.02102], [13.51501, 8.51501, 6.02102]]
overlap: true
ff: ["lib.niticr.meam", "niticr.meam"]
output: ["Step", "TotEng", "PotEng", "Temp"]