job_name: smaller_interface_rel
sim: md
elems: Ni Ti Cr
xyz: criniti_interface.xyz
system_bounds: [[-8.9863, 0.0, 0.0], [6.35681, 14.8326, 10.4882]]
overlap: false
ff: ["lib.niticr.meam", "niticr.meam"]
output: ["Step", "TotEng", "PotEng", "Temp"]