job_name: interface_ti
sim: ti
elems: Ni Ti Cr
xyz: interface_smd_frames.xyz
system_bounds: [[-41.4273, -8.51501, -6.02102], [23.51501, 8.51501, 6.02102]]
overlap: false
ff: ["lib.niticr.meam", "niticr.meam"]
output: ["PotEng", "Temp", "f_1[1]", "f_1[2]", "f_1[3]", "f_2[1]", "f_2[2]", "f_2[3]"]