job_name: niti111_freeti_double_dmd
sim: dmd_bulk_rel
elems: Ni Ti
xyz: niti111_6-6-6ti.xyz
system_bounds: [[0, 0, 0], [43.6143, 25.1808, 50.84]]
overlap: false
ff: ["NiTi_graph_compress.pb"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "source /data/apps/go.sh\nsource /home/dsharm23/.bashrc\nload_dplmp\n"
resources:
  queue: "parallel"
  walltime: "72:0:0"
  cores: 48