job_name: niti_unit_dmd
sim: dmd_unit_rel
elems: Ni Ti
xyz: niti.xyz
system_bounds: [[0, 0, 0], [3.015, 3.015, 3.015]]
overlap: true
ff: ["NiTi_graph_v1.pb"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "source /data/apps/go.sh\nsource /home/dsharm23/.bashrc\nload_dplmp\n"
resources:
  queue: "express"
  walltime: "2:0:0"
  cores: 1