job_name: niti_free_slab_nidouble_dmd
sim: dmd_bulk_rel
elems: Ni Ti
xyz: bulk_niti_10-10-10ni.xyz
system_bounds: [[0, 0, 0], [29.6758, 29.6758, 49.6758]]
overlap: false
ff: ["NiTi_graph_compress.pb"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "source /data/apps/go.sh\nsource /home/dsharm23/.bashrc\nload_dplmp\n"
resources:
  queue: "parallel"
  walltime: "72:0:0"
  cores: 48