job_name: niti111_freeti_double_eam
sim: eam_bulk_rel
elems: Ni Ti
xyz: niti111_6-6-6ti.xyz
system_bounds: [[0, 0, 0], [43.6143, 25.1808, 50.84]]
overlap: false
ff: ["niti2024.eam.fs"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "8:0:0"
  cores: 8