job_name: niti_free_slab_tidouble_eam
sim: eam_bulk_rel
elems: Ni Ti
xyz: bulk_niti_10-10-10ti.xyz
system_bounds: [[0, 0, 0], [29.6758, 29.6758, 49.6758]]
overlap: false
ff: ["niti2024.eam.fs"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "8:0:0"
  cores: 8