job_name: crniti_001_ni
sim: meam_bulk_rel
elems: Ni Ti Cr
xyz: crniti_interface_10-10-5ni.xyz
system_bounds: [[0, 0, 0], [29.6758, 29.6758, 46.1232]]
overlap: false
ff: ["lib.niticr.meam", "niticr.meam"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "8:0:0"
  cores: 8