job_name: cr110_free_double_2001
sim: meam_bulk_rel
elems: Cr
xyz: cr110_10-10-10.xyz
system_bounds: [[0, 0, 0], [40.6615, 28.752, 60.6615]]
overlap: false
ff: ["lib_cr2001.meam", "cr2001.meam"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "24:0:0"
  cores: 8