job_name: crniti_110_ti
pmf_type: ti
sim: meam_interface_ti
elems: Ni Ti Cr
xyz: crniti110_ti_frames.xyz
system_bounds: [[0, 0, 0], [41.9679, 29.6758, 57.5]]
overlap: false
ff: ["lib.niticrv1.meam", "niticr_v1.meam"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "24:0:0"
  cores: 24