job_name: cr_free_slab_double_2001
sim: meam_bulk_rel
elems: Cr
xyz: bulk_cr_10-10-10.xyz
system_bounds: [[0, 0, 0], [28.572, 28.572, 48.572]]
overlap: false
ff: ["lib_cr2001.meam", "cr2001.meam"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "12:0:0"
  cores: 8