job_name: niti_free_slab_ti_2019
sim: meam_bulk_rel
elems: Ni Ti
xyz: bulk_niti_10-10-5ti.xyz
system_bounds: [[0, 0, 0], [29.6758, 29.6758, 29.8379]]
overlap: false
ff: ["lib_niti2019.meam", "niti2019.meam"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "8:0:0"
  cores: 8