job_name: niti110_free_double_2019
sim: meam_bulk_rel
elems: Ni Ti
xyz: niti110_10-10-10.xyz
system_bounds: [[0, 0, 0], [41.9679, 29.6758, 61.8679]]
overlap: false
ff: ["lib_niti2019.meam", "niti2019.meam"]
output: ["step", "etotal", "cella", "cellb", "cellc", "cellalpha", "cellbeta", "cellgamma"]
prebash: "ml cl-lammps\nsource /data/apps/go.sh\n"
resources:
  queue: "shared"
  walltime: "24:0:0"
  cores: 8