job_name: ti_555_2nn
sim: neb
elems: ["Ti"]
lattice: 3.29194
system_bounds: 5 15 5
xyz: ti_555_2nn.first.xyz
overlap: False
ff: ti2004.eam
data: ti_555_2nn.init.data
image_base: ti_555_2nn.image
id: ["147"]
output: []